import { Inter } from "next/font/google";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { AuthProvider } from "./Providers";
import { ThemeProvider } from "./(components)/theme-provider";
import "@radix-ui/themes/styles.css";
import Nav from "./(components)/Nav";
import NavWrap from "./(components)/NavWrap";
// config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CrescentByte",
  description: "Generated by local idiot",
};

// we import provider here and wrap the childern with it
export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <AuthProvider>
          {/* HTML error is from them */}
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <NavWrap>{children}</NavWrap>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
