import { Inter } from "next/font/google";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { AuthProvider } from "./Providers";
import { Theme, ThemePanel } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import Nav from "./(components)/Nav";
import NavWrap from "./(components)/NavWrap";
// config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CrescentByte",
  description: "Generated by local idiot",
};

// we import provider here and wrap the childern with it
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {/* HTML error is from them */}
          {/* <Theme appearance="dark"> */}
          <NavWrap>{children}</NavWrap>
          {/* <ThemePanel /> */}
          {/* </Theme> */}
        </AuthProvider>
      </body>
    </html>
  );
}
